keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH:https://keycloak-tsplatform.techsophy.com}/auth/realms/
  realm.name: ${KEYCLOAK_REALM_NAME:techsophy-platform}

ADD_ALLOWEDHEADER: '*'
ADD_ALLOWEDMETHOD: '*'
CORS_ALLOWEDORIGINS: '*'

springdoc:
  version: '@springdoc.version@'


spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      #      discovery:
      #        locator:
      #          enabled: true
      routes:
        - id: form-modeler-service
          uri: http://form-app:8080
          predicates:
            - Path=/api/form-modeler/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: process-modeler-service
          uri: http://workflow-app:8080
          predicates:
            - Path=/api/process-modeler/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: rule-modeler-service
          uri: http://rule-app:8080
          predicates:
            - Path=/api/rule-modeler/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: case-modeler-service
          uri: http://case-app:8080
          predicates:
            - Path=/api/case-modeler/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: core-app
          uri: http://core-app:8080
          predicates:
            - Path=/api/core/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: accounts-service
          uri: http://account-app:8080
          predicates:
            - Path=/api/accounts/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: rules-service
          uri: http://rules:8080
          predicates:
            - Path=/api/rules/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: form-runtime-service
          uri: http://runtime-form-app:8080
          predicates:
            - Path=/api/form-runtime/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: admin-service
          uri: http://admin-app:8080
          predicates:
            - Path=/api/admin/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: keycloak
          uri: https://keycloak-tsplatform.techsophy.com
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: workflow-service
          uri: http://uxapp-controller:8080
          predicates:
            - Path=/api/workflow/**
          filters:
            - StripPrefix=1
        - id: workflow-engine-rest
          uri: http://workflow-engine:8080
          predicates:
            - Path=/api/camunda/engine-rest/**
          filters:
            - StripPrefix=1
        - id: camunda
          uri: http://workflow-engine:8080
          predicates:
            - Path=/api/camunda/service/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://tp-app-notification:8080
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=1
        - id: template-modeler-service
          uri: http://template-app:8080
          predicates:
            - Path=/api/template-modeler/**
          filters:
            - StripPrefix=1
        - id: document-converter-service
          uri: http://document-converter:8080
          predicates:
            - Path=/api/document-converter/**
          filters:
            - StripPrefix=1
        - id: tp-pdf-convertor
          uri: http://tp-pdf-convertor:8080
          predicates:
            - Path=/api/pdf-converter/**
          filters:
            - StripPrefix=1
        - id: deployment-service
          uri: http://deployment-app:8080
          predicates:
            - Path=/api/deployment/**
          filters:
            - StripPrefix=1
        - id: dms-service
          uri: http://dms-app:8080
          predicates:
            - Path=/api/dms/**
          filters:
            - StripPrefix=1
        - id: openapi
          uri: http://gateway:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - RewritePath=/v3/api-docs/(?<path>.*), /api/$\{path}/v3/api-docs
        - id: config-server
          uri:  http://cloud-config-server:8080
          predicates:
            - Path=/api/config-server/**
          filters:
            - StripPrefix=1
        - id: checklist-modeler-service
          uri: http://checklist-app:8080
          predicates:
            - Path=/api/checklist-modeler/**
          filters:
            - StripPrefix=1
        - id: checklist-engine-service
          uri: http://checklist-engine:8080
          predicates:
            - Path=/api/checklist-engine/**
          filters:
            - StripPrefix=1
        - id: pci-service
          uri: http://pci-app:8080
          predicates:
            - Path=/api/pci/**
          filters:
            - StripPrefix=1
        - id: scheduler-service
          uri: http://scheduler-app:8080
          predicates:
            - Path=/api/scheduler/**
          filters:
            - StripPrefix=1
        - id: escalation-matrix-modeler-service
          uri: http://escalation-matrix-app:8080
          predicates:
            - Path=/api/escalation-matrix-modeler/**,/api/dynamic-steps-modeler/**
          filters:
            - StripPrefix=1
        - id: escalation-matrix-runtime-service
          uri: http://runtime-escalation-matrix:8080
          predicates:
            - Path=/api/escalation-matrix-runtime/**,/api/dynamic-steps-runtime/**
          filters:
            - StripPrefix=1
        - id: payment-gateway-service
          uri: http://payment-gateway:8080
          predicates:
            - Path=/api/payment-gateway/**
          filters:
            - StripPrefix=1
        - id: elastic-service
          uri: http://tp-elastic-search-app:8080
          predicates:
            - Path=/api/elastic/**
          filters:
            - StripPrefix=1
        - id: util-service
          uri: http://util-app:8080
          predicates:
            - Path=/api/util/**
          filters:
            - StripPrefix=1
        - id: pcil-core-service
          uri: http://pcil-core:8080
          predicates:
            - Path=/api/pcil-core/**
          filters:
            - StripPrefix=1
        - id: pcil-erp-sync-service
          uri: http://pcil-erp-sync:8080
          predicates:
            - Path=/api/pcil-erp-sync/**
          filters:
            - StripPrefix=1
        - id: crm-service
          uri: http://connector-suite-crm:8080
          predicates:
            - Path=/api/crm/**
          filters:
            - StripPrefix=1
        - id: insta-service
          uri: http://connector-insta:8080
          predicates:
            - Path=/api/insta/**
          filters:
            - StripPrefix=1
        - id: debezium-service
          uri: http://debezium:8080
          predicates:
            - Path=/api/debezium/**
          filters:
            - StripPrefix=1
        - id: start-service
          uri: http://hello-python-service:5000
          predicates:
            - Path=/api/start/**
          filters:
            - StripPrefix=1
        - id: stop-service
          uri: http://hello-python-service:5000
          predicates:
            - Path=/api/stop/**
          filters:
            - StripPrefix=1
        - id: runtime-template-service
          uri: http://runtime-template:8080
          predicates:
            - Path=/api/runtime-template/**
          filters:
            - StripPrefix=1
        - id: task-management-service
          uri: http://task-management-app:8080
          predicates:
            - Path=/api/task-management/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}${keycloak.realm.name}
      client:
        provider:
          keycloak:
            token-uri: ${keycloak.issuer-uri}${keycloak.realm.name}/protocol/openid-connect/token
            authorization-uri: ${keycloak.issuer-uri}${keycloak.realm.name}/protocol/openid-connect/auth
            userinfo-uri: ${keycloak.issuer-uri}${keycloak.realm.name}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-without-test-scope:
            provider: keycloak
            client-id: ${keycloak.client.id}
            client-secret: ${keycloak.client.secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"





logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE

logging.pattern.console: "%d{HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

security:
  disabled:
    baseUrl:
      - /**/config-server/**
