spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/${KEYCLOAK_REALM_NAME}


gateway:
  uri: ${GATEWAY_URI}
  
keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/

camunda-engine.servlet.context-path : ${CAMUNDA_ENGINE_CONTEXT_PATH}

shared-workflow-engine: ${SHARED_WORKFLOW_ENGINE:true}

springdoc:
  api-docs:
    path: workflow/v3/api-docs

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        evenrConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
database:
#  url: ${TP_MODELER_APP_MONGO_URI}
  name: techsophy-platform
        
