springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /debezium/v3/api-docs

gateway:
  uri: ${GATEWAY_URI}

database:
  hostname: ${DB_HOSTNAME}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbName: ${DB_NAME}
  primaryKey: ${PRIMARY_KEY}

offset:
  filePath: ${OFFSET_FILEPATH}

slot:
  name: ${SLOT}

table:
  whitelist: ${WHITELIST:}

  ## Elasticsearch properties
spring:
  elasticsearch:
    uris: ${ELASTIC_URI}

logging:
  level:
    org:
      springframework:
        web: INFO
  
  ## Actuator config
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
