spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/

default:
  pagelimit: 5


springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /elastic/v3/api-docs

elasticsearch:
  protocol: ${PROTOCOL}
  enable: true
  host: ${HOST}
  port: ${PORT}

gateway:
  uri: ${GATEWAY_URI}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        evenrConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED